//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gazete
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int AdminId { get; set; }
        public string AdminAd { get; set; }
        public string AdminSifre { get; set; }
    }
}
