//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gazete
{
    using System;
    using System.Collections.Generic;
    
    public partial class yazilar
    {
        public int yaziId { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public string resim { get; set; }
        public Nullable<int> slide { get; set; }
        public Nullable<int> sirano { get; set; }
        public Nullable<int> akif { get; set; }
        public Nullable<int> yazarId { get; set; }
    }
}
